# Generated by Django 4.2.23 on 2025-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=64)),
                ('logo', models.ImageField(upload_to='pages_img')),
                ('img', models.ImageField(upload_to='pages_img')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_paragraph', models.TextField()),
                ('university_name', models.CharField(max_length=64)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('img', models.ImageField(upload_to='sections_img')),
                ('phone_number', models.CharField(default='+998', max_length=16)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('years', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
