# Generated by Django 4.2.23 on 2025-08-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer_logos/')),
                ('text', models.TextField()),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number3', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number4', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='links_logos/')),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date_time', models.DateTimeField()),
                ('text', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pages_img')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pages_img')),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_paragraph', models.TextField()),
                ('university_name', models.CharField(blank=True, max_length=64, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='sections_img')),
                ('phone_number', models.CharField(blank=True, default='+998', max_length=16, null=True)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('years', models.CharField(blank=True, max_length=4, null=True)),
                ('title_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.titlemodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newsmodel')),
            ],
        ),
    ]
