# Generated by Django 4.2.23 on 2025-08-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='text',
            new_name='text1',
        ),
    ]
