# Generated by Django 5.2.5 on 2025-08-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='footer_logos/')),
                ('text', models.TextField()),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number3', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number4', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='links_logos/')),
                ('url_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('date_time', models.DateTimeField()),
                ('text', models.TextField()),
                ('text2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
